export const DESCRIPTION_CHANGED = 'description_changed'
export const EMOJI_CHANGED = 'emoji_changed'
// export const LOGIN_USER_ATTEMPT = 'login_user_attempt'
// export const LOGIN_USER_SUCCESS = 'login_user_success'
// export const LOGIN_USER_FAILURE = 'login_user_failure'
